### PR TITLE
Changes for conduits, and async exception protection

### PR DESCRIPTION
**Pull request by snoyberg**
This contains two completely orthogonal changes:
- Expose a (take|destroy|put)Resource API so that we can use resources more naturally with a system like conduits (not need to invert control). Comments explain that `takeResource` should be used with caution.
- Apply `mask` to `withResource` to ensure proper resource destruction in the case of an async exception.

### CODE REVIEW

**Comment by bos** [comment]
Thanks, Michael!

**Comment by snoyberg** [comment]
Thanks for merging. Two quick questions:
- Do you know what version number this will be released under?
- Do you have a timeframe on when it will be released?

I'm hoping to put out a Yesod beta soon, and I want to know if I should include this patched resource-pool on the Yackage server.

**Comment by bos** [comment]
I just released it. Thanks for prompting me :)

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
