### PR TITLE
Use controlIO directly instead of onException

### PR DESCRIPTION
**Pull request by basvandijk**
Hi Bryan,

Attached is a little patch which should make `withResource` slightly faster in case an exception is thrown in the given action. I haven't profiled it and maybe the performance improvement is not worth the trouble since it's only happening in exceptional cases. So, just see what you do with it.

Regards,

Bas

### CODE REVIEW

**Comment by bos** [comment]
Thanks, Bas! I've applied your change, although I cannot say I understand what it does :-\

**Comment by basvandijk** [comment]
Hi Bryan,

I'm planning to restructure the package and rename most functions to make it more clear what everything does. Of course the documentation should also be improved. I'm planning to finish this before September. But here's a little description:

[`controlIO`]((http://hackage.haskell.org/packages/archive/monad-control/0.2.0.1/doc/html/Control-Monad-IO-Control.html#v:controlIO) behaves much like `liftIO`: it lifts an `IO` computation in your monad `m`. 

But before it does that, it captures the state of `m` (if it has any). Additionally it provides a "run function" to your `IO` computation that allows you to run an `m` computation inside `IO` on this captured state.

If you look at the type of `controlIO` you will notice that the given `IO` computation must return an `m` computation. This is perhaps the most confusing part of the function. This returned `m` computation is used to restore the state of the `m` computation that you executed in the given `IO` computation. (Note that: `controlIO = join . liftControlIO`)

This restore `m` computation is returned by the "run function" so make sure to return it from the `IO` action. 

Regards,

Bas

**Comment by bos** [comment]
Thanks for the explanation! Where does the extra efficiency you mentioned
come from?

**Comment by basvandijk** [comment]
Previously you used the `onException` from `monad-control`:

```
onException ∷ MonadControlIO m ⇒ m α → m β → m α
onException m what = controlIO $ \runInIO →
                       E.onException (runInIO m)
                                     (runInIO what)
```

If you look at the type you'll see that the exception handler `what` is also an `m` computation. If you look at the implementation you'll see that because of this we need to apply our "run function" `runInIO` to `what`.

Because your exception handler is already in `IO` this extra `runInIO` is unneeded. So basically all I did was remove the redundant `runInIO`:

```
onException ∷ MonadControlIO m ⇒ m α → IO β → m α
onException m what = controlIO $ \runInIO →
                       E.onException (runInIO m)
                                     what
```

Note that this will only give a performance improvement when an exception is raised.

**Pull request merged**
